# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-modules-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-node-modules-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules
            - cypress
            - cypress.json
            - package.json
      - run: npm run test-ci
  deploy:
    docker:
      - image: circleci/node:8.11-browsers
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run: npm run build
      - run: npx now ./dist --token $NOW_TOKEN --public
      - run: cd dist && npx now alias set heineken-team.now.sh --token $NOW_TOKEN
  e2e:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
          CYPRESS_BASE_URL: https://heineken-team.now.sh
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Running E2E tests
          command: npm run test-sit
      - store_test_results:
          path: cypress/testresults
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots


workflows:
  # Use CircleCI API version 2
  version: 2

  # Define the `commit` workflow
  commit:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - e2e:
          requires:
            - deploy
